services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
     - MYSQL_DATABASE=paysystem
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_ROOT_HOST=%
     - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pay-system_my_network

  redis:
    image: redis:latest
    container_name: redis-paysystem
    ports:
      - "6380:6379"
    networks:
      - pay-system_my_network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - pay-system_my_network

  common-service:
    build:
      context: ./common
      dockerfile: Dockerfile
    container_name: common-service
    ports:
      - "9001:9001"
    depends_on:
      - mysql
      - eureka-server
      - gateway-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/paysystem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pay-system_my_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "9002:9002"
    depends_on:
      - mysql
      - eureka-server
      - gateway-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/paysystem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
      #- REDIRECT_URI=https://061b-222-110-244-103.ngrok-free.app/api/users/login/kakao/redirect
    networks:
      - pay-system_my_network

  streaming-service:
    build:
      context: ./streaming-service
      dockerfile: Dockerfile
    container_name: streaming-service
    ports:
      - "9003:9003"
    depends_on:
      - mysql
      - eureka-server
      - gateway-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/paysystem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pay-system_my_network

  revenue-service:
    build:
      context: ./revenue-service
      dockerfile: Dockerfile
    container_name: revenue-service
    ports:
      - "9004:9004"
    depends_on:
      - mysql
      - redis
      - eureka-server
      - gateway-service
    environment:
      - SPRING_REDIS_HOST=redis-paysystem
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/paysystem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pay-system_my_network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pay-system_my_network

volumes:
  mysql-data:

networks:
  pay-system_my_network:
    driver: bridge