INSERT INTO paysystem.ads (ads_id,ads_url) VALUES (1, 'https://example.com/ad1'),
 (2, 'https://example.com/ad2'),
 (3, 'https://example.com/ad3'),
 (4, 'https://example.com/ad4'),
 (5, 'https://example.com/ad5'),
 (6, 'https://example.com/ad6'),
 (7, 'https://example.com/ad7'),
 (8, 'https://example.com/ad8'),
 (9, 'https://example.com/ad9'),
 (10, 'https://example.com/ad10'),
 (11, 'https://example.com/ad11'),
 (12, 'https://example.com/ad12'),
 (13, 'https://example.com/ad13'),
 (14, 'https://example.com/ad14'),
 (15, 'https://example.com/ad15'),
 (16, 'https://example.com/ad16'),
 (17, 'https://example.com/ad17'),
 (18, 'https://example.com/ad18'),
 (19, 'https://example.com/ad19'),
 (20, 'https://example.com/ad20');

INSERT INTO paysystem.video (id, duration, video_views, video_url) VALUES
                                                           (1, 6, 0, 'https://example.com/video/1'),
                                                           (2, 1, 0, 'https://example.com/video/2'),
                                                           (3, 20, 0, 'https://example.com/video/3'),
                                                           (4, 8, 0,'https://example.com/video/4'),
                                                           (5, 17, 0, 'https://example.com/video/5'),
                                                           (6, 20, 0, 'https://example.com/video/6'),
                                                           (7, 11, 0, 'https://example.com/video/7'),
                                                           (8, 63, 0, 'https://example.com/video/8'),
                                                           (9, 20, 0, 'https://example.com/video/9'),
                                                           (10, 10, 0, 'https://example.com/video/10'),
                                                           (11, 8, 0, 'https://example.com/video/11'),
                                                           (12, 20, 0, 'https://example.com/video/12'),
                                                           (13, 11, 0, 'https://example.com/video/13'),
                                                           (14, 12, 0, 'https://example.com/video/14'),
                                                           (15, 13, 0, 'https://example.com/video/15'),
                                                           (16, 20, 0, 'https://example.com/video/16'),
                                                           (17, 9, 0, 'https://example.com/video/17'),
                                                           (18, 20, 0, 'https://example.com/video/18'),
                                                           (19, 71, 0, 'https://example.com/video/19'),
                                                           (20, 17, 0, 'https://example.com/video/20'),
                                                           (21, 20, 0, 'https://example.com/video/21'),
                                                           (22, 41, 0, 'https://example.com/video/22'),
                                                           (23, 20, 0, 'https://example.com/video/23'),
                                                           (24, 16, 0, 'https://example.com/video/24'),
                                                           (25, 20, 0, 'https://example.com/video/25'),
                                                           (26, 20, 0, 'https://example.com/video/26'),
                                                           (27, 15, 0, 'https://example.com/video/27'),
                                                           (28, 17, 0, 'https://example.com/video/28'),
                                                           (29, 3, 0, 'https://example.com/video/29'),
                                                           (30, 57, 0, 'https://example.com/video/30');


